# Generated by Django 5.1.5 on 2025-01-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rent",
                    models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
                ),
                ("beds", models.IntegerField(default=3)),
                ("baths", models.IntegerField(default=3)),
                ("square_feet", models.IntegerField(default=1000)),
                ("address", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="")),
                ("contact", models.IntegerField(default=1234567890)),
            ],
        ),
    ]
