# Generated by Django 5.1.5 on 2025-01-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="id",
        ),
        migrations.AddField(
            model_name="house",
            name="oid",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
