# Generated by Django 5.1.5 on 2025-05-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("housing", "0002_remove_house_id_house_oid"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="More_infomation",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="square_feet",
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
