# Generated by Django 5.1.5 on 2025-05-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("housing", "0002_remove_house_id_house_oid"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="moreInfo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
