# Generated by Django 5.1.5 on 2025-05-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("housing", "0003_house_more_infomation_alter_house_square_feet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="oid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
