# Generated by Django 5.1.5 on 2026-01-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_savedhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='contact',
            field=models.CharField(default='Number, Email, or Social Media etc.'),
        ),
    ]
