# Generated by Django 5.1.5 on 2026-01-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_alter_house_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='More_infomation',
            new_name='More_information',
        ),
    ]
