# Generated by Django 5.1.5 on 2026-01-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_rename_more_infomation_house_more_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='contact',
            field=models.CharField(default='Number, Email, or Social Media etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='square_feet',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
