# Generated by Django 5.1.5 on 2026-05-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_house_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='listing_type',
            field=models.CharField(choices=[('long_term', 'Long Term'), ('sublet', 'Sublet/Short Term')], default='sublet', max_length=20),
        ),
    ]
