# Generated by Django 5.1.5 on 2026-05-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0010_house_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='auto_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
